config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  root 'posts#index'
  resources :posts, only: %i[index create destroy]

  get '/auth/:provider/callback', to: 'sessions#create', as: :signin
  delete '/logout', to: 'sessions#destroy', as: :logout
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, [Post]

    return unless user.present?

    if user.admin_role?
      can :manage, :all
      return
    end

    if user.user_role?
      can :manage, Post, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  include CableReady::Broadcaster

  belongs_to :user
  before_save { body.squeeze! }
  validates :body, presence: true, length: { maximum: 200 }

  # TODO Transfer code from Model to ActiveJob
  after_create do
    cable_ready['feed'].insert_adjacent_html(
      selector: '#pinned-post',
      position: 'afterend',
      html: ApplicationController.render(partial: 'posts/post', locals: { post: self, editable: false })
    )
    cable_ready.broadcast
  end

  after_destroy do
    cable_ready['feed'].remove(
      selector: '#post_' + id.to_s
    )
    cable_ready.broadcast
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :posts, dependent: :destroy

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.find_or_create_from_auth_hash(auth_hash)
    puts auth_hash
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      name: auth_hash.info.name,
      avatar: auth_hash.extra.raw_info.photo_400_orig
    )
    user
  end

  def remember
    self.remember_token = new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private

  def new_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      redirect_to root_path, notice: 'Невозможно добавить сообщение'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    remember(@user)
    redirect_to root_path
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile
    User.where(admin_role: true).first
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      session[:user_id] = user.id
      @current_user = user
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/_flashes.html.slim
- flash.each do |key, message|
  p class="#{key}"
    = message

app/views/layouts/_header.html.slim
header.header
  = inline_svg 'icons/sun.svg', size: '15px', class: 'svg-contrast'
  .switch.header__switch
      input.switch__input type="checkbox" id="themeSwitch"
      label.switch__label aria-hidden="true" for="themeSwitch" on
      .switch__marker aria-hidden="true"
  = inline_svg 'icons/moon.svg', size: '14px', class: 'svg-contrast'
  .header__right
    - if current_user
      .header__avatar
        img src='#{current_user.avatar}'
      = link_to logout_path, method: :delete, class: :header__exit do
        = inline_svg 'icons/door.svg', size: '25px', class: 'svg-contrast'
    - else
      .header__auth
        = link_to '/auth/vkontakte', method: :post, class: 'button button_primary' do
          = inline_svg 'icons/vk.svg', size: '20px'
          span Войти

app/views/layouts/_profile.html.slim
.profile
  .profile__avatar
    - if profile
      img src="#{profile.avatar}"
  h1.profile__username = profile&.name
  .profile__details
    p.profile__line Ruby on Rails разработчик
    p.profile__line
      a href="https://github.com/berdni" target="_blank" github.com/berdni
    p.profile__line @berdni
  .profile__group-button
    a.button.button_primary href="https://twitter.com/berdnidz3" target="_blank"
      = inline_svg 'icons/twitter.svg', size: '20px'
      span Подписаться
    a.button.button_contrast-lower href="https://twitter.com/berdnidz3" target="_blank"
      span Написать
  .profile__title Образование
  span.profile__text
    | 2017-2021г. Студент 4 курса бакалавриата автоматики и вычислительной
        техники Новосибирского государственного технического университета
  .profile__title Мои проекты
  span.profile__text
    a> href="https://mobile-pw.ru/" target="_blank" Mobile-pw
    | - фансайт посвященный мобильной игре Perfect World Mobile
  a href="https://github.com/berdni"
    = inline_svg 'icons/github.svg', size: '20px', class: 'svg-contrast'
  a href="https://t.me/BeKonich"
    = inline_svg 'icons/telegram.svg', size: '20px', class: 'svg-contrast'
  a href="https://vk.com/rk300"
    = inline_svg 'icons/vk.svg', size: '20px', class: 'svg-contrast'
  a href="https://twitter.com/berdnidz3"
    = inline_svg 'icons/twitter.svg', size: '20px', class: 'svg-contrast'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Berdni
    == csrf_meta_tags
    == csp_meta_tag

    meta name="viewport" content="width=device-width, initial-scale=1"
    link rel="shortcut icon" type="image/png" href="/favicon.png"

    == stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    == javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    == render 'layouts/header'
    section.page
      .page__container
        aside.page__side
          == render 'layouts/profile'
        .page__content
            == yield

app/views/posts/_form.html.slim
= form_with model: @post, local: true,
  html: { class: 'post', 'data-controller': 'posts' } do |form|
  .post__block
    .post__left
      .post__avatar
        img src='#{current_user.avatar}'
    .post__right
      = form.text_area :body, placeholder: 'Поделитесь мнением',
        class: 'post__input', 'data-action': 'input->posts#validate'
      = form.submit 'Отправить', class: 'post__button button button_primary',
        disabled: true, 'data-target': 'posts.submit'

app/views/posts/_pinned_post.html.slim
.post#pinned-post
  .post__pin
    = inline_svg 'icons/pin.svg', size: '15px'
    | Закрепленный пост
  .post__block
    .post__left
      .post__avatar
        - if profile
          img src="#{profile.avatar}"
    .post__right
      .post__username
        = profile&.name
      .post__text
        span Мои навыки:
        ul
          li
            | <b>Ruby</b> 2 и новее
          li
            | <b>Ruby on Rails</b> 4.0 и новее
          li
            | <b>SQL, Redis</b>
          li
            | <b>HTML, SLIM, CSS/SCSS, JavaScript</b> для простого фронтенда
          li
            | <b>Nginx</b> и <b>Puma</b> для запуска приложений
          li
            | <b>Heroku</b> или <b>VPS</b> для развертвывания приложений
          li
            | Некоторый опыт работы с <b>React</b>

app/views/posts/_post.html.slim
.post id="#{dom_id(post)}" data-controller="posts"
  .post__block
    .post__left
      .post__avatar
        img src='#{post.user.avatar}'
    .post__right
      .post__username
        = post.user.name
      .post__text
        = post.body
      - if editable && can?(:manage, post)
        .post__action
          = link_to 'Удалить', post_path(post),
            method: :delete, data: { confirm: 'Вы уверены?' }

app/views/posts/index.html.slim
.feed
  - if current_user
    = render 'layouts/flashes'
    = render 'form'
  = render 'pinned_post'
  = render partial: 'post', collection: @posts, locals: { editable: true }